"""add roadmap task progress

Revision ID: 2426471be1a1
Revises: 42105b821ccb
Create Date: 2026-09-04 10:57:09.920133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2426471be1a1'
down_revision: Union[str, Sequence[str], None] = '42105b821ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_roadmaps', sa.Column('completed_tasks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_roadmaps', 'completed_tasks')
    # ### end Alembic commands ###
