"""add coding assessment tables

Revision ID: 2e7ba778c111
Revises: 89bc9e286c91
Create Date: 2026-09-04 09:54:17.541368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7ba778c111'
down_revision: Union[str, Sequence[str], None] = '89bc9e286c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('test_cases', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_problems_id'), 'coding_problems', ['id'], unique=False)
    op.create_table('coding_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_submissions_id'), 'coding_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_coding_submissions_problem_id'), 'coding_submissions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_coding_submissions_user_id'), 'coding_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coding_submissions_user_id'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_problem_id'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_id'), table_name='coding_submissions')
    op.drop_table('coding_submissions')
    op.drop_index(op.f('ix_coding_problems_id'), table_name='coding_problems')
    op.drop_table('coding_problems')
    # ### end Alembic commands ###
