"""add daily plan tasks

Revision ID: 46fc67fb2d61
Revises: 2426471be1a1
Create Date: 2026-09-04 18:02:37.097101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fc67fb2d61'
down_revision: Union[str, Sequence[str], None] = '2426471be1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plan_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('task_index', sa.Integer(), nullable=False),
    sa.Column('task_text', sa.Text(), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_date', 'task_index', name='uq_daily_plan_user_date_task')
    )
    op.create_index(op.f('ix_daily_plan_tasks_id'), 'daily_plan_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_daily_plan_tasks_plan_date'), 'daily_plan_tasks', ['plan_date'], unique=False)
    op.create_index(op.f('ix_daily_plan_tasks_user_id'), 'daily_plan_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_plan_tasks_user_id'), table_name='daily_plan_tasks')
    op.drop_index(op.f('ix_daily_plan_tasks_plan_date'), table_name='daily_plan_tasks')
    op.drop_index(op.f('ix_daily_plan_tasks_id'), table_name='daily_plan_tasks')
    op.drop_table('daily_plan_tasks')
    # ### end Alembic commands ###
