"""add placement readiness

Revision ID: b694e58cace8
Revises: 2e7ba778c111
Create Date: 2026-09-04 10:14:51.087258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b694e58cace8'
down_revision: Union[str, Sequence[str], None] = '2e7ba778c111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_readiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('resume_score', sa.Integer(), nullable=False),
    sa.Column('job_match_score', sa.Integer(), nullable=False),
    sa.Column('interview_score', sa.Integer(), nullable=False),
    sa.Column('coding_score', sa.Integer(), nullable=False),
    sa.Column('skill_progress', sa.Integer(), nullable=False),
    sa.Column('readiness_level', sa.String(length=50), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_readiness_id'), 'placement_readiness', ['id'], unique=False)
    op.create_index(op.f('ix_placement_readiness_user_id'), 'placement_readiness', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placement_readiness_user_id'), table_name='placement_readiness')
    op.drop_index(op.f('ix_placement_readiness_id'), table_name='placement_readiness')
    op.drop_table('placement_readiness')
    # ### end Alembic commands ###
