"""add career roadmap

Revision ID: d5da3beb1585
Revises: b694e58cace8
Create Date: 2026-09-04 10:35:39.108225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5da3beb1585'
down_revision: Union[str, Sequence[str], None] = 'b694e58cace8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_description_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('overall_progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('roadmap_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_roadmaps_id'), 'career_roadmaps', ['id'], unique=False)
    op.create_index(op.f('ix_career_roadmaps_job_description_id'), 'career_roadmaps', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_career_roadmaps_user_id'), 'career_roadmaps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_roadmaps_user_id'), table_name='career_roadmaps')
    op.drop_index(op.f('ix_career_roadmaps_job_description_id'), table_name='career_roadmaps')
    op.drop_index(op.f('ix_career_roadmaps_id'), table_name='career_roadmaps')
    op.drop_table('career_roadmaps')
    # ### end Alembic commands ###
